# for building auto-code-rover:latest
FROM yuntongzhang/swe-bench:latest

RUN git config --global user.email acr@nus.edu.sg
RUN git config --global user.name acr

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y vim build-essential libssl-dev

COPY environment.yml /opt/auto-code-rover/environment.yml
COPY requirements*.txt /opt/auto-code-rover/

WORKDIR /opt/auto-code-rover
RUN conda env create -f environment.yml

COPY . /opt/auto-code-rover

# for arise
RUN wget -qO- https://astral.sh/uv/install.sh | sh
ENV ARISE_DIRECTORY=/opt/arise

ENTRYPOINT [ "/bin/bash" ]
